/**
 * Regenerates the embedded font modules of `@openview/engine` from a directory of pinned faces.
 *
 * Usage: node tools/fonts/generate.mjs <directory holding the twelve ttf files>
 *        pnpm run lint:fix
 *
 * The second step is not optional: the modules are written in a canonical shape and Biome owns
 * their final formatting, so a regeneration that skips it leaves the lint gate red.
 *
 * Every face is checked against its pinned length and SHA-256 before anything is written, so a
 * substituted file stops the generator instead of silently changing what every render embeds.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { cssFamilyOf, FACES, RELEASES } from './sources.mjs';
import { coverageOf, namesOf, stylesOf } from './ttf.mjs';

const BARREL = 'packages/engine/src/document/fonts/generated.ts';
const FACES_DIR = 'packages/engine/src/document/fonts/generated';

/**
 * One module per face, plus a barrel that orders them.
 *
 * Biome skips any file over one mebibyte, and a single module holding the twelve faces is seven of
 * them: split, every generated byte stays under the same lint and plugin checks as hand-written
 * code, with no change to the shared configuration.
 */
const slugOf = (face) => `${face.family}-${face.weight}-${face.style}`.replaceAll('.', '-');

const bindingOf = (face) => slugOf(face).replaceAll('-', '_');

const directory = process.argv[2];
if (directory === undefined) {
  throw new Error('usage: node tools/fonts/generate.mjs <directory of pinned ttf files>');
}

const faces = FACES.map((face) => {
  const bytes = new Uint8Array(readFileSync(join(directory, face.file)));
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  if (bytes.length !== face.byteLength || sha256 !== face.sha256) {
    throw new Error(
      `${face.file} does not match its pin: ${bytes.length}/${sha256} instead of ${face.byteLength}/${face.sha256}`,
    );
  }
  const styles = stylesOf(bytes);
  if (styles.weight !== face.weight || styles.italic !== (face.style === 'italic')) {
    throw new Error(`${face.file} declares weight ${styles.weight}, italic ${styles.italic}`);
  }
  const names = namesOf(bytes);
  return {
    ...face,
    sha256,
    slug: slugOf(face),
    binding: bindingOf(face),
    data: Buffer.from(bytes).toString('base64'),
    codePoints: coverageOf(bytes),
    familyName: names.get(1),
    subfamilyName: names.get(2),
  };
});

const lines = (parts) => parts.join('\n');

const moduleOf = (face) =>
  lines([
    `/** ${face.familyName} ${face.subfamilyName}, generated -- do not edit by hand. */`,
    `import type { BundledFontFace } from '../types.js';`,
    '',
    'export const FACE: BundledFontFace = {',
    `  family: '${face.family}',`,
    `  cssFamily: '${cssFamilyOf(face.family)}',`,
    `  weight: ${face.weight},`,
    `  style: '${face.style}',`,
    `  byteLength: ${face.byteLength},`,
    `  sha256: '${face.sha256}',`,
    `  familyName: ${JSON.stringify(face.familyName)},`,
    `  subfamilyName: ${JSON.stringify(face.subfamilyName)},`,
    `  codePoints: [${face.codePoints.map(([from, to]) => `[${from}, ${to}]`).join(', ')}],`,
    `  data: '${face.data}',`,
    '};',
    '',
  ]);

const barrelOf = () =>
  lines([
    '/**',
    ' * Every embedded face, generated -- do not edit by hand.',
    ' *',
    ' * Regenerate with `node tools/fonts/generate.mjs <directory>`; the pins live in',
    ' * `tools/fonts/sources.mjs` and the licences in `packages/engine/NOTICE`. The test beside this',
    ' * module re-reads these bytes with its own TrueType reader and refuses any drift.',
    ' */',
    ...faces.map(
      (face) => `import { FACE as ${face.binding} } from './generated/${face.slug}.js';`,
    ),
    `import type { BundledFontFace } from './types.js';`,
    '',
    '/** In catalogue order: family by family, then regular, bold, italic, bold italic. */',
    'export const GENERATED_FACES: readonly BundledFontFace[] = [',
    ...faces.map((face) => `  ${face.binding},`),
    '];',
    '',
  ]);

rmSync(FACES_DIR, { recursive: true, force: true });
mkdirSync(FACES_DIR, { recursive: true });
for (const face of faces) {
  writeFileSync(join(FACES_DIR, `${face.slug}.ts`), moduleOf(face), 'utf8');
}
writeFileSync(BARREL, barrelOf(), 'utf8');

for (const face of faces) {
  const points = face.codePoints.reduce((total, [from, to]) => total + (to - from + 1), 0);
  console.log(
    `${face.file.padEnd(26)} ${String(face.byteLength).padStart(7)} B  ${String(face.codePoints.length).padStart(4)} ranges  ${String(points).padStart(5)} code points`,
  );
}
const total = faces.reduce((sum, face) => sum + face.data.length, 0);
console.log(`\n${faces.length} faces, ${(total / 1024 / 1024).toFixed(2)} MiB of base64`);
console.log(
  Object.values(RELEASES)
    .map((release) => `${release.name} ${release.version} (${release.licence})`)
    .join(', '),
);
