# Organisation SonarCloud
sonar.organization=patayencroute

# Key required for SonarQube / SonarCloud
sonar.projectKey=PatayEnCroute_Openview
sonar.projectName=Openview
sonar.projectVersion=0.1.0

# Source directories for analysis
sonar.sources=packages/core/src,packages/designer/src,packages/engine/src,packages/viewer/src,apps/playground/src

# Test files
sonar.tests=packages/core/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Exclusions
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/dist/**,**/node_modules/**,apps/playground/**
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/dist/**

# Path to LCOV test coverage report
sonar.javascript.lcov.reportPaths=packages/core/coverage/lcov.info

# Source encoding
sonar.sourceEncoding=UTF-8
